<?php
    
    # Created by Mi-Jung Ko
    # All rights reserved
    # This php file is used to try charging.
    # Insert to the user's database and sends it to the seller's database
    
    
    # GET parameter from url
    
    $pubKey = $_GET['pubKey'];
    $amount = $_GET['amount'];
    
    
    
    /* EasyBitcoin-PHP
     A simple class for making calls to Bitcoin's API using PHP.
     https://github.com/aceat64/EasyBitcoin-PHP
     
     ========================================
     The MIT License (MIT)
     Copyright (c) 2013 Andrew LeCody
     ======================================== */
    
    require_once('easybitcoin.php');
    
    
    
    # create object
    # Bitcoin('username', 'password', 'localhost*', 'port number**'
    # localhost* is your loopback address
    # port number** is BTC regtest mode's port number(18443)
    
    $username = 'bitcoinrpc';
    $password = 'testuser1!';
    $localhost = '127.0.0.1';
    $port_number = '18443';
    
    $bitcoin = new Bitcoin($username, $password, $localhost, $port_number);
    
    
    
    // ///////////////////////////
    
    
    # balance_before is balance before the transaction.
    
    $balance_before = $bitcoin->getbalance();
    //echo "your balance before transaction : ".$balance_before;
    
    
    // ///////////////////////////
    
    
    # send a transaction command to the bitcoin network
    # and get tx_id that is generated by this transaction.
    
    $tx_id = $bitcoin->sendtoaddress($pubKey,$amount);
    
    
    # get user information from BTC network
    
    $info = $bitcoin->getwalletinfo();
    $HDmasterKey = $info['hdmasterkeyid'];
    
    
    
    # create array structure for JSON encoding
    
    $user_info = array('HDmasterKey' => $HDmasterKey, 'tx_id' => $tx_id);
    
    # JSON encoding for printing on the web
    
    echo json_encode($user_info);
    
    
    
    
    
    // ///////////////////////////
    
    
    
    
    # balance_after is balance after the transaction.
    
    $balance_after = $bitcoin->getbalance();
    
    //echo "your balance after transaction : ".$balance_after;
    
?>
